const screens=[...document.querySelectorAll(".screen")];let current="welcome";
function show(id){const n=document.getElementById(id);if(!n||id===current)return;screens.forEach(x=>x.classList.remove("active"));n.classList.add("active");current=id;window.scrollTo({top:0,behavior:"smooth"});burst(5)}
document.querySelectorAll("[data-next]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.next)));
function burst(n=5){for(let i=0;i<n;i++){const x=document.createElement("span");x.textContent=Math.random()>.25?"♥":"✦";x.style.cssText=`position:fixed;left:${40+Math.random()*20}%;top:${45+Math.random()*15}%;z-index:9;color:#ed6688;pointer-events:none;font-size:${15+Math.random()*12}px;animation:fly .9s ease-out forwards;`;document.body.appendChild(x);setTimeout(()=>x.remove(),1000)}}
const rx=["Today you have full permission to ignore everyone.","Prescription: one stupid joke immediately. 😂","Your cough has officially been reported to HR. Please cooperate. 😭","Doctor's orders: water, rest and absolutely zero overthinking. 😌","Side effect of resting: you might accidentally feel better. 🌷"];let ri=0;
document.getElementById("dose").onclick=()=>{document.getElementById("prescriptionText").innerHTML=rx[ri++%rx.length].replace("😂","😂");document.getElementById("prescriptionCard").animate([{transform:"rotate(-1deg) scale(.96)"},{transform:"rotate(1deg) scale(1.03)"},{transform:"rotate(-1deg) scale(1)"}],{duration:450});burst(4)};
let taps=0;document.querySelectorAll(".message-grid button").forEach(b=>b.onclick=()=>{document.getElementById("messageResult").textContent=b.dataset.message;b.animate([{transform:"scale(.96)"},{transform:"scale(1.04)"},{transform:"scale(1)"}],{duration:300});if(++taps>=2)document.getElementById("nightBtn").classList.remove("hidden");burst(3)});
document.getElementById("nightBtn").onclick=()=>show("night");

let score=0,time=20,timer,spawner,best=Number(localStorage.getItem("thejuBest")||0);document.getElementById("best").textContent=best;const game=document.getElementById("game");
function spawn(){const b=document.createElement("button");b.className="target";b.textContent=Math.random()>.2?"❤️":"💗";b.style.left=5+Math.random()*88+"%";b.style.top=7+Math.random()*78+"%";b.onclick=()=>{score++;document.getElementById("score").textContent=score;b.remove();burst(1)};game.appendChild(b);setTimeout(()=>b.remove(),850)}
document.getElementById("play").onclick=()=>{clearInterval(timer);clearInterval(spawner);score=0;time=20;document.getElementById("score").textContent=0;document.getElementById("time").textContent=20;document.getElementById("result").textContent="";game.querySelector(".ready")?.remove();const btn=document.getElementById("play");btn.disabled=true;btn.textContent="Catch them! ❤️";spawner=setInterval(spawn,500);timer=setInterval(()=>{time--;document.getElementById("time").textContent=time;if(time<=0){clearInterval(timer);clearInterval(spawner);game.querySelectorAll(".target").forEach(x=>x.remove());btn.disabled=false;btn.textContent="Play again →";if(score>best){best=score;localStorage.setItem("thejuBest",best);document.getElementById("best").textContent=best}document.getElementById("result").textContent=score>=10?`You caught ${score} hearts. You're doing great. 😌❤️`:`You caught ${score} hearts. That's enough smiling for today. 🥺❤️`;document.getElementById("afterGame").classList.remove("hidden");burst(10)}},1000)};
document.getElementById("restBtn").onclick=()=>{document.getElementById("restBtn").classList.add("hidden");document.getElementById("final").classList.remove("hidden");burst(14)};

document.getElementById('afterGame').addEventListener('click',()=>show('company'));
